### ISSUE TITLE
GPC_4T - HAS 0.1

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core#1]
High-Level-Architecture-Specifications 
- [ ] Skeleton
- [ ] Include diagram
- [ ] List Of Opens

**Comment by amichai-bd** [comment]
For example you may ask a question from here 
@SaarKadosh

**Comment by amichai-bd** [comment]
Looks like your HAS is all ready for RTL0.1 - please mark this task as done by closing this task.
![image](https://user-images.githubusercontent.com/81047407/116151259-0e299c00-a6ed-11eb-9bb8-b096de480ca6.png)

**Comment by adlv888** [comment]
HAS ready for 0.1
