### ISSUE TITLE
GPC_4T - Upload a PPT with the Core Data Path

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core#11]
- [ ] add PPT in the doc/ folder.
- [ ] For Each instruction in the RV32I ISA Please add a Slide with the DataPath+Ctrl Bits highlights.
- [ ] List the Ctrl Bit in a Slide and explain why they are needed.
- [ ] Add a Slide with a Table of all Instructions -> for each Instruction Set the Ctrl Bits.
Use the riscv-Spec sheet (see doc/<spec>)  to determine the data path for each instruction.

**Comment by adlv888** [comment]
I believe the ppt is ready for 0.1 what do you think?

**Comment by amichai-bd** [comment]
I agree - i have some notes regarding the diagram.
So its probably better to discuss the PPT before you finalize the drawing.

You may close this issue
