### ISSUE TITLE
GPC_4T - MAS 0.1

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core#2]
Micro-Architecture-Specification
- [ ] Skeleton
- [ ] Include diagram
- [ ] List Of Opens-Specification

**Comment by amichai-bd** [comment]
Looks like you MAS  is al ready for RTL0.1 - please mart this task as done by closing this task.
![image](https://user-images.githubusercontent.com/81047407/116151259-0e299c00-a6ed-11eb-9bb8-b096de480ca6.png)

**Comment by adlv888** [comment]
MAS ready for 0.1
