### ISSUE TITLE
GPC_4T - FIX Typo in branch_comp logic

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core#23]
we Using the same ALU input for the  branch_comp logic.  (Should use "AluIn1Q102H" vs "AluIn2Q102H"
See here:  
![image](https://user-images.githubusercontent.com/81047407/115986302-36fc4500-a5b8-11eb-84bd-638687bf808b.png)

**Comment by adlv888** [comment]
you are correct . will be fixed

**Comment by adlv888** [comment]
done
