### ISSUE TITLE
LOTR - Testing the Project Manager tasks assignment #4

### ISSUE THREAD

**Issue by amichai-bd** [amichai-bd/riscv-multi-core#5]
- [x] see if you can mark this as done
- [x] See if you can move this task to "In progress"  
- [x] See if you can mark this as "Done"

**Comment by amichai-bd** [comment]
Any update regarding the bullets:  
>  - [ ] See if you can move this task to "In progress"
>  - [ ] See if you can mark this as "Done"
@SaarKadosh 
@tzahiperetz

**Comment by tzahiperetz** [comment]
okay
